# Generated by Django 4.1.3 on 2023-03-07 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
