# Generated by Django 4.1.3 on 2023-03-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
