# Generated by Django 4.1.3 on 2023-01-02 11:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultrasound',
            name='Fix_problem',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='ultrasound',
            name='Photo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ultrasound',
            name='Problem',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ultrasound',
            name='Reason',
            field=models.CharField(max_length=1000),
        ),
    ]
