# Generated by Django 4.1.3 on 2023-01-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0002_alter_ultrasound_fix_problem_alter_ultrasound_photo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ultrasound',
        ),
    ]
