# Generated by Django 4.1.3 on 2023-01-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ultrasound',
        ),
    ]
