# Generated by Django 4.1.3 on 2023-01-20 14:35

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meds', '0005_delete_ultrasound'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ultrasound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(choices=[('GE Healthcare', 'GE Healthcare'), ('Samsung', 'Samsung'), ('Hitachi', 'Hitachi'), ('Philips', 'Philips'), ('Siemens', 'Siemens'), ('Toshiba', 'Toshiba'), ('Aloka', 'Aloka')], max_length=255)),
                ('Model', models.CharField(max_length=255)),
                ('Problem', models.CharField(max_length=1000)),
                ('Reason', models.CharField(max_length=1000)),
                ('Fix_problem', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
