# Generated by Django 4.1.3 on 2023-01-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ultrasound',
        ),
    ]
