# Generated by Django 4.1.3 on 2023-01-29 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0008_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='med',
            old_name='fix_problem',
            new_name='fixproblem',
        ),
    ]
