# Generated by Django 4.1.3 on 2023-03-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0009_rename_fix_problem_med_fixproblem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='med',
            name='brand',
            field=models.CharField(choices=[('GE Healthcare', 'GE Healthcare'), ('Samsung', 'Samsung'), ('Hitachi', 'Hitachi'), ('Philips', 'Philips'), ('Siemens', 'Siemens'), ('Toshiba', 'Toshiba'), ('Aloka', 'Aloka'), ('Khác', 'Khác')], max_length=255),
        ),
    ]
