# Generated by Django 4.1.3 on 2023-03-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0010_alter_med_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='med',
            name='fixproblem',
            field=models.CharField(max_length=3000),
        ),
    ]
