# Generated by Django 4.1.3 on 2023-01-22 16:54

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Med',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('GE Healthcare', 'GE Healthcare'), ('Samsung', 'Samsung'), ('Hitachi', 'Hitachi'), ('Philips', 'Philips'), ('Siemens', 'Siemens'), ('Toshiba', 'Toshiba'), ('Aloka', 'Aloka')], max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('problem', models.CharField(max_length=1000)),
                ('reason', models.CharField(max_length=1000)),
                ('fix_problem', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
