# Generated by Django 4.1.3 on 2023-01-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_med'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Med',
        ),
    ]
